### PR TITLE
Handle `insert_table` errors

### PR DESCRIPTION
**Pull request by couralex6**
Fix for issue #128 

Attempting to resolve the issue of unhandled insert errors with a new dataclass `InsertTableErrorResult` which can handle the `error` field.

This is most likely not the most elegant way to handle this. I'm open to suggestions :)

### CODE REVIEW

**Comment by bh2smith** [comment]
I like the solution although it doesn't quite follow the pattern we're using everywhere else. If you check the api/execution.py file you'll see this common pattern of try catch key error and then raise of dune error. Realistically we should improve the error classifications, but it might be good to try to follow the similar pattern for now so we can find all the things that need changing after improvements have been made.

**Review by bh2smith — APPROVED** [review]

**Review by bh2smith — APPROVED** [review]

**Review by bh2smith — CHANGES_REQUESTED** [review]
Please throw the error.

**Comment by bh2smith** [comment]
Looks good for now! I think improving error handling as a whole could be reserved for a follow up PR. let's get this in for now and address that separately. Let me know if you're happy with this and we can get it released.

**Review by bh2smith — APPROVED** [review]

**Review by waddahAldrobi — APPROVED** [review]
Agree with the comments above

**Pull request merged**
